name: Run Tests #CI/CD

on: push
jobs:
  run-tests: #CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  deploy:
    name: Deploy #CD
    runs-on: ubuntu-20.04
    needs: run-tests # alleen bij succes
    steps:
      - name: Login on droplet and update main.py
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROLET_IP }} # host is in dit geval het IP adres
          username: ${{ secrets.DIGITAL_OCEAN_USER }} # The default username is root
          key: ${{ secrets.SSH_PRIVATE_KEY }} # hier moet de SSH private key in komen/ aanmaken op droplet
          port: ${{ secrets.SSH_PORT }} # veranderen of laten staan op 22?
          run: echo "Hello, World!"        
          #script: |

              # nog uitzoeken

